### Tarun 
POST http://localhost:4000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDIzZDk5YmNkN2E4OTA2YzczNWY0YzgiLCJmaXJzdE5hbWUiOiJUYXJ1biIsImxhc3ROYW1lIjoiR2lyaXNoIiwicGFzc3dvcmQiOiIkMmIkMTAkZGhSRGgzdjg5TnF0WkJFaU1OVW5NdXA5bTlSN3o0VHJCYWlaOGNkdWVRMWdoZGcuS1Q1c2EiLCJlbWFpbCI6IlRhcnVuQG1lLmNvbSIsImNyZWF0ZWRBdCI6IjIwMjEtMDItMTBUMTM6MDM6MjMuNzE1WiIsInVwZGF0ZWRBdCI6IjIwMjEtMDItMTBUMTM6MDM6MjMuNzE1WiIsIl9fdiI6MCwiaWF0IjoxNjEyOTYzMjg5fQ.b1e-lIFIf4I7ACvTStPmT3VgCgxS3t7Ft66vm0oErX0
Content-Type: application/json

{
"productName": "Advil",
"quantity": 10
}


### Vincent
POST http://localhost:4000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDIzZDliZWNkN2E4OTA2YzczNWY0YzkiLCJmaXJzdE5hbWUiOiJWaW5jZW50IiwibGFzdE5hbWUiOiJBbG9qYWRvIiwicGFzc3dvcmQiOiIkMmIkMTAkNXlCNXR6SWpEWHNYTWdrQ3ZhWlBodXRUbmdwaE01SWg3R2lWOVp1ZUZoZGw4OHZYNmN0ZmEiLCJlbWFpbCI6IlZpbmNlbnRAbWUuY29tIiwiZG9jdG9yc051bWJlciI6Iig4ODkpIDQxNS0zMzIxIiwibG9jYXRpb24iOiJPYWtsYW5kLCBDYWxpZm9ybmlhIiwiY3JlYXRlZEF0IjoiMjAyMS0wMi0xMFQxMzowMzo1OC4yMjBaIiwidXBkYXRlZEF0IjoiMjAyMS0wMi0xMFQxMzowMzo1OC4yMjBaIiwiX192IjowLCJpYXQiOjE2MTI5NjM2OTd9.cmzCPHX50MfS8CLc3SmO5J30CrANFBNqcFQRUXR8ycQ
Content-Type: application/json

{
"productName": "Covid Vacine",
"quantity": 5
}
